apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: hashicorp
  annotations:
    kubernetes.io/ingress.class: "nginx-vault"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: vault
spec:
    rules:
    - host: vault.k8s.rsletten.com
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: vault-active
              port:
                number: 8200
